# Generated by Django 2.1.1 on 2018-09-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backvalley', '0002_auto_20180927_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='employees',
            field=models.ManyToManyField(to='backvalley.Employee'),
        ),
    ]
