version: '2.1'

services:
  db:
    restart: always
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backvalley:
    restart: always
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    image: backvalley
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: